### ISSUE TITLE
Delete All servisinin yazılması 

### ISSUE THREAD

**Issue by turakahmet** [teamoftarnet/springMVC#13]
Intellijde,
Service deleteAllRestaurant
Dao deleteAllRestaurant
Controller
class ve interface lerin yazılması. Çalıştırılıp tüm restaurantlar silinmesi kontrolü sağlanmalı.

**Comment by efealigulocak** [comment]
Restaurantları silen servisler ve ilgili class,interfeceler oluşturulmuştur.
