### ISSUE TITLE
Veri tabanı tablosu oluşturma

### ISSUE THREAD

**Issue by turakahmet** [teamoftarnet/springMVC#16]
Veri tabanı Oracle da  bir adet tablo oluşturulması bu tabloda tüm verilerin işlenmesi restoran user puanlama v.b tüm kriterler ele alınarak bir tablo şeması çıkarılması ve tablo ilişkilerinin kurulması.

**Comment by burcudurmusogluu** [comment]
bu iş tamamlandı.
